### ISSUE TITLE
Update @noble/hashes

### ISSUE THREAD

**Issue by fiatjaf** [paulmillr/micro-bip39#2]
I'm not sure about why JavaScript package managers are so bad or maybe I'm missing something, but it seems that this package uses @noble/hashes 0.5.5 while other packages of the same suite are using @noble/hashes 0.5.7, which means the dependency is fetched and bundled twice?

**Comment by paulmillr** [comment]
This package specifies `^0.5.5` which would use 0.5.7 if it's available and other dep requires `0.5.7`. This follows `semver`.

Duplication happens because if your bundler -- not because of `bip39`
